language: android
  
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0

matrix:
  include:
    - env: LAZ_VER=1.8.0RC5 android=false
    - env: LAZ_VER=1.8RC5  LAZ_ENV=wine LAZ_OPT="--os=win32 --cpu=i386" android=false
    - env: LAZ_VER=1.8.0RC5  android=true FPC_VER=3.0.4

android:
  components:
    - tools
    - platform-tools
    - tools

install:
  - git clone https://github.com/benibela/travis-lazarus travis-lazarus
  - travis-lazarus/.travis.install.py
  - if [[ "$LAZ_ENV" = wine ]]; then find $WINEPREFIX -iname '*fpc.cfg' | head -1 | xargs -i{} ln {} ~/.fpc.cfg; ls -l ~; fi
  - if [[ ! -e ~/.fpc.cfg ]]; then echo '#INCLUDE /etc/fpc.cfg' > ~/.fpc.cfg; fi 
  - cd ..
  #get dependencies from sourceforge
  - (hg clone http://hg.code.sf.net/p/videlibri/code sf) || (sleep $( echo $$ | head -c 2); hg clone http://hg.code.sf.net/p/videlibri/code sf) || (sleep 60; hg clone http://hg.code.sf.net/p/videlibri/code sf) || (sleep 60; hg clone http://hg.code.sf.net/p/videlibri/code sf) 
  - | 
    cd sf
    hg pull && hg update default
    rm -rf programs/internet/VideLibri; mv ../videlibri programs/internet/VideLibri
    mkdir import; git clone https://github.com/benibela/flre.git import/flre; 
    echo -Fu$PWD/import/flre/src/         >> ~/.fpc.cfg
    echo -Fi$PWD/components/pascal/       >> ~/.fpc.cfg
    echo -Fi$PWD/components/pascal/data   >> ~/.fpc.cfg
    echo -Fu$PWD/components/pascal/data   >> ~/.fpc.cfg
    ln -s $PWD/import/flre components/pascal/import/flre > /dev/null
  - |
    if [[ $android = true ]]; then 
      yes | sdkmanager ndk-bundle "build-tools;28.0.3"  "platforms;android-28";
      sudo apt-get install -y gcc-arm-linux-androideabi libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386;
      oldpath=$PWD;
      cd ..
      svn checkout https://svn.freepascal.org/svn/fpc/trunk fpc      
      cd fpc
      sudo -E $oldpath/programs/internet/VideLibri/android/manage.sh setupbinutils /usr/bin
      sudo -E $oldpath/programs/internet/VideLibri/android/manage.sh setupfpccrosscompile
      cd $oldpath;
      $oldpath/programs/internet/VideLibri/android/manage.sh setupfpccrosscfg >> ~/.fpc.cfg
      mkdir -p ~/.gradle;
      echo 'ANDROID_STORE_PASSWORD=F2XyHtMYmG65GQimSQmm4WDD' > ~/.gradle/gradle.properties;
      echo 'ANDROID_KEY_PASSWORD=F2XyHtMYmG65GQimSQmm4WDD' >> ~/.gradle/gradle.properties;
      echo 'ANDROID_GLOBAL_KEYSTORE=/tmp/keystore' >> ~/.gradle/gradle.properties;
      keytool -genkey -no-prompt -keystore /tmp/keystore -alias videlibri -keyalg RSA -keysize 2048 -validity 10000 -storepass F2XyHtMYmG65GQimSQmm4WDD -keypass F2XyHtMYmG65GQimSQmm4WDD -dname "CN=travis, OU=ID, O=T, L=T, S=T, C=T";      
    fi
  - |
    if [[ $LAZ_ENV = wine ]]; then  
      sudo apt-get install -y dos2unix;
      tee programs/internet/xidel/xidel <<<$'#!/bin/bash
        winargs=()
        for arg in "$@"; do
          winargs+=(${arg/\/home\/travis/Z:\\\\home\\\\travis})
        done
        wine ../../../xidel/xidel.exe --extract-exclude line-ending -e \'line-ending:=x:cps(10)\' "${winargs[@]}" | dos2unix | perl -pne \' s!(file://Z:[^"]+)! {my $temp = $1; $temp =~ s%(Z:)?\\\\{1,2}%/%g; $temp}!ge\'
      ';
      chmod +x programs/internet/xidel/xidel;
    fi
  - if [[ -z "$LAZ_ENV" ]] && [[ $android = false ]]; then 
      sudo apt-get install fakeroot lintian;
    fi
  - cat ~/.fpc.cfg

#    svn checkout -r 37480 https://svn.freepascal.org/svn/fpc/trunk	fpc-trunk
#    cd fpc-trunk
      
      
script:
  - ls -l
  - umask 0022
  - lazbuild $LAZ_OPT --add-package components/pascal/data/searchbarpackage.lpk
  - lazbuild $LAZ_OPT --add-package components/pascal/data/treelistviewpackage.lpk
  - lazbuild $LAZ_OPT --add-package components/pascal/internettools.lpk
  - touch programs/internet/xidel/xidelbuilddata.inc; lazbuild $LAZ_OPT programs/internet/xidel/xidel.lpi
  - lazbuild $LAZ_OPT programs/internet/VideLibri/_meta/assetversiontests.lpi
  - basepath=$PWD
  - if [[ $android = false ]]; then lazbuild $LAZ_OPT programs/internet/VideLibri/bookWatch.lpi; fi
  - if [[ $android = true ]]; then cd programs/internet/VideLibri/android; ./manage.sh build; fi
  - export PATH=$PATH:$PWD/programs/internet/xidel/
  - cd $basepath; $LAZ_ENV programs/internet/VideLibri/_meta/assetversiontests
  - if [[ -z "$LAZ_ENV" ]] && [[ $android = false ]]; then 
      cd $basepath/programs/internet/VideLibri && ./_meta/build.deb.sh && lintian *.deb;
    fi
  - cd $basepath/programs/internet/VideLibri/_meta/tests;  ./unittests.sh

notifications:
  email:
    on_failure: change