name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;23.1.7779620" "tools" "build-tools;30.0.3"  "platforms;android-30"
    - run: git clone https://github.com/benibela/xidel.git
    - run: xidel/.github/download-dependencies.sh && xidel/.github/setup-fpc-cfg.sh 
    - name: Install FreePascal for Android
      run: |
        sudo apt-get install fpc
        oldpath=$PWD;
        git clone https://gitlab.com/freepascal.org/fpc/source.git --depth 1 --single-branch -b fixes_3_2 fpc
        cd fpc
        sudo $oldpath/android/manage.sh setupbinutils /usr/bin
        sudo $oldpath/android/manage.sh setupfpccrosscompile
        cd $oldpath;
        android/manage.sh setupfpccrosscfg >> ~/.fpc.cfg
    - name: Build VideLibri
      run: |
        sed -e '/PASDBL/d' -i internettools/internettoolsconfig.inc
        echo -Fi$PWD/internettools/data >> ~/.fpc.cfg
        echo -Fu$PWD/internettools/data >> ~/.fpc.cfg
        echo -Fu$PWD/internettools/internet >> ~/.fpc.cfg
        echo -Fu$PWD/internettools/system >> ~/.fpc.cfg
        android/manage.sh fakesignature
        cd android
        ./manage.sh build release
        ./manage.sh symbols
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        path: android/android/build/outputs/apk/release/android-release.apk
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        path: android/android/build/outputs/bundle/release/android-release.aab
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        name: android-symbols
        path: android/symbols/
