name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;23.2.8568313"  "tools" "build-tools;30.0.3"  "platforms;android-30"
    - name: debug github actions
      run: echo $ANDROID_HOME
           sudo bash -c echo '$ANDROID_HOME'
    - run: git clone https://github.com/benibela/xidel.git
    - run: xidel/.github/download-dependencies.sh && xidel/.github/setup-fpc-cfg.sh 
    - name: Install FreePascal for Android
      run: |
        oldpath=$PWD;
        sudo -E $oldpath/android/manage.sh setupbinutils /usr/bin
        sudo apt-get install fpc
        git clone https://gitlab.com/freepascal.org/fpc/source.git --depth 1 --single-branch -b fixes_3_2 fpc
        cd fpc
        sudo $oldpath/android/manage.sh setupfpccrosscompile
        cd $oldpath;
        android/manage.sh setupfpccrosscfg >> ~/.fpc.cfg
    - name: Build VideLibri
      run: |
        #Disable PasDblStrUtils
        sed -e '/PASDBL/d' -i internettools/internettoolsconfig.inc
        #Set additional path
        echo -Fi$PWD/internettools/data >> ~/.fpc.cfg
        echo -Fu$PWD/internettools/data >> ~/.fpc.cfg
        echo -Fu$PWD/internettools/internet >> ~/.fpc.cfg
        echo -Fu$PWD/internettools/system >> ~/.fpc.cfg
        #fix binutils
        which i686-linux-android-strip
        which aarch64-linux-android-strip
        which arm-linux-androideabi-strip
        which x86_64-linux-android-strip
        sudo mkdir -p /usr/local/lib/android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/
        sudo ln -srfv $(which i686-linux-android-strip) /usr/local/lib/android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/
        sudo ln -srfv $(which aarch64-linux-android-strip) /usr/local/lib/android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/
        sudo ln -srfv $(which arm-linux-androideabi-strip) /usr/local/lib/android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/
        sudo ln -srfv $(which x86_64-linux-android-strip) /usr/local/lib/android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/bin/
        #Start building
        android/manage.sh fakesignature
        cd android
        ./manage.sh build release
        ./manage.sh symbols
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        name: videlibri.apk
        path: android/android/build/outputs/apk/release/android-release.apk
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        name: videlibri.aab
        path: android/android/build/outputs/bundle/release/android-release.aab
    - name: 'Upload '
      uses: actions/upload-artifact@v3
      with:
        name: android-symbols
        path: android/symbols/
